// 'use client'
import type { Metadata } from "next";
import Web3Provider from "./utils/Web3Provider";
import localFont from "next/font/local";
import "./globals.css";
import "./page.scss";
import "./fonts.scss";
import Header from "./components/header/header";
import Footer from "./components/footer/footer";
import SocialsFooter from "./components/socialsFooter/socialsFooter";




export const metadata: Metadata = {
  title: "The Recruits",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Web3Provider>
        <body >
          <div className="page" >
            <Header />
            <main>
              {children}
            </main>
            <SocialsFooter/>
            <Footer/>
          </div>
        </body>
      </Web3Provider>
    </html>
  );
}